name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test_foreman:
    name: Test with Foreman
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/../foreman
    steps:
      - uses: actions/checkout@v4

      - name: Clone Foreman
        run: git clone --branch develop https://github.com/theforeman/foreman.git ../foreman

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Configure local theforeman-rubocop
        run: |
          bundle config local.theforeman-rubocop $GITHUB_WORKSPACE
          bundle install

      - name: Run RuboCop validation
        run: bundle exec rubocop --config $GITHUB_WORKSPACE/.rubocop.yml

  test_katello:
    name: Test with Katello
    runs-on: ubuntu-latest
    needs: test_foreman
    defaults:
      run:
        working-directory: ${{ github.workspace }}/../katello
    steps:
      - uses: actions/checkout@v4

      - name: Clone Katello
        run: git clone --branch develop https://github.com/theforeman/katello.git ../katello

      - name: Clone Foreman
        run: git clone --branch develop https://github.com/theforeman/foreman.git ../foreman

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Configure local dependencies
        run: |
          bundle config local.theforeman-rubocop $GITHUB_WORKSPACE
          bundle config local.foreman $GITHUB_WORKSPACE/../foreman
          bundle install

      - name: Run RuboCop validation
        run: bundle exec rubocop --config $GITHUB_WORKSPACE/.rubocop.yml
