name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test_foreman:
    name: Test with Foreman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  

      - name: Clone Foreman
        run: git clone --branch develop https://github.com/theforeman/foreman.git ../foreman

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Test with Foreman
        run: |
          cd ../foreman
          bundle config local.theforeman-rubocop $GITHUB_WORKSPACE
          bundle exec rubocop --config $GITHUB_WORKSPACE/.rubocop.yml

  test_katello:
    name: Test with Katello
    runs-on: ubuntu-latest
    needs: test_foreman
    steps:
      - uses: actions/checkout@v4

      - name: Clone Katello
        run: git clone --branch develop https://github.com/theforeman/katello.git ../katello

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Test with Katello
        run: |
          cd ../katello
          bundle config local.theforeman-rubocop $GITHUB_WORKSPACE
          bundle config local.foreman $GITHUB_WORKSPACE/../foreman
          bundle exec rubocop --config $GITHUB_WORKSPACE/.rubocop.yml
